In [2]:
a=2
b=3

In [4]:
b+3

6

integers: 2,3,4,5

floats: 2.0, 3.4, 6.7

Strings: "david", 'david', '2.0', '3'

booleans: True, False

In [11]:
li=['23','3','767']

In [12]:
li=[int(i) for i in li]
li

[23, 3, 767]

In [13]:
sum(li)

793

In [14]:
list(range(0,len(li)))

[0, 1, 2]

In [9]:
del(li[0])

In [10]:
li

[3, 767]

In [ ]:
print(a+b)

In [8]:
"david"*2

'daviddavid'

In [10]:
("david"+" ")*2

'david david '

In [11]:
print("add:", a+b)

add: 5


In [12]:
print("subtract:", a-b)

subtract: -1


In [13]:
print("multiply:", a*b)

multiply: 6


In [14]:
print("power:", a**b)

power: 8


In [32]:
print("modular:", 51%2)

modular: 1



### Division


In [19]:
#division
print(10/4)


2.5


In [21]:
print(10//4)

2


### Comparison

>, <, <=, >=, !=,  == 

In [22]:
a==10

False

In [24]:
a==2

True

#### Logical operators
not, and, or

In [26]:
a

2

### Data types and Operations
* Data Types: Integers, Floats, Booleans, Strings
* 
Operators: Arithmetic, Assignment, Comparison, Logical

In [33]:
type(22)    

int

In [34]:
type('2')

str

In [35]:
type(True)

bool

In [36]:
type(2.0)

float

In [37]:
number="2"

In [39]:
type(int(number)) #convert to integer

int

In [40]:
int(False)

0

## Assigment operator

In [ ]:
a=12


In [ ]:
a

### Arithmetic operators

* addition, subtraction, division(integer,float), power, modular division
* Built-In Functions, Type Conversion
  
In this quiz you're going to do some calculations for a tiler. Two parts of a floor need tiling. One part is 9 tiles wide by 7 tiles long, the other is 5 tiles wide by 7 tiles long. Tiles come in packages of 6.
* 
How many tiles are neede

* ?
You buy 17 packages of tiles containing 6 tiles each. How many tiles will be left over?

In [ ]:
print(a+a, a-2, a//5,  a/5)

In [ ]:
a**2

In [ ]:
a%2

Built-In Functions, Type Conversion

Booleans, Comparison Operators, and Logical Operators

True, False, ==, <, >, <=, >=, !=,  or and,  not


## Data Structures

Lists, tuples, dictionaries, sets

List methods: len, sum, sorted, 


In [42]:
#list
names = ["Carol", "Albert", "Ben", "Donna"]
sb=[2,4,5,6,8,8]
list1=[[4,5],['3','come', True, False], 4]

In [46]:
names

['Carol', 'Albert', 'Ben', 'Donna']

In [51]:
print(names[0],',', names[3])

Carol , Donna


In [58]:
names[-1]=3

In [53]:
names[-2]

'Ben'

In [55]:
names[0:3]

['Carol', 'Albert', 'Ben']

In [56]:
names[2:]

['Ben', 'Donna']

In [57]:
names[:-2]

['Carol', 'Albert']

In [59]:
names

['Carol', 'Albert', 'Ben', 3]

### Tuple

In [60]:
sb1=(2,4,5,6,8,8)

## sets

In [64]:
set1=set(sb1)

In [65]:
set1

{2, 4, 5, 6, 8}

## dictionary

In [66]:
dic1 = {"a": 11, "b": 12, "c": 36, "v": True}

In [67]:
type(dic1)

dict

In [69]:
dic1.keys()

dict_keys(['a', 'b', 'c', 'v'])

In [70]:
dic1.values()

dict_values([11, 12, 36, True])

## control flows

If statements
If, Elif, Else

In [71]:
#if we have 5 students, the class will proceed
n=6
if n >= 5:
    print('Proceed with the class')

Proceed with the class


In [72]:
n=4
if n >= 5:
    print('Proceed with the class')

In [73]:
#if we have 5 students, the class will proceed otherwise do not

In [75]:
n=13
if n>=5:
    print('Proceed with the class')
else:
    print('Do not proceed with the class')

Proceed with the class


In [76]:
# grading: F:<40, pass 40 <= x< 50, Second class above 50, first class above or equal to 70  

In [80]:
marks= 40
if marks <40:
    print('Fail')
elif marks < 50:
    print('pass')
elif marks < 70:
    print('Second class upper or Lower')
else:
    print('first class')

pass


In [81]:
# grading: Fail:<40, passed 40 <= x<= 100, (marks > 100) or (marks < 0): Invalid score  

loops
For and while loop


## Functions

Population Density Function
Write a function named population_density that takes two arguments, population and land_area, and returns a population density calculated from those values.


Find area, average, standard deviation, median, mode


In [92]:
def add2numbers(a,b):
    '''
    This function calculates the sum of two numbers and returns a number
    Arguments a = number, b=number    
    '''
    return a+b

In [87]:
v=add2numbers(10,7)

In [85]:
var2=10+7

In [86]:
var2

17

In [88]:
v

17

In [91]:
#area of a triangle with base = 24, hypotenuse= 25: 
#defne the function and class it
# area= (base * height)/2
#height=(hypotenuse**2 -base**2)**(1/2)

In [95]:
def area_of_tri(base,hyp):
    hei=(hyp**2 - base**2)**0.5
    area=0.5*base*hei
    return area

In [96]:
area_of_tri(24,25)

84.0

In [97]:
lis=[3,2,4,8,9,8]
len(lis)

6

In [99]:
s=sum(lis)
s

34

In [100]:
sum(lis)/len(lis)

5.666666666666667

In [101]:
def average_f(a_list):
    return sum(a_list)/len(a_list)

In [102]:
average_f(lis)

5.666666666666667

In [103]:
lis

[3, 2, 4, 8, 9, 8]

In [104]:
for i in lis:
    print(i)

3
2
4
8
9
8


In [107]:
sum1=0
for i in lis:
    sum1=sum1+i
print(sum1)


34


In [112]:
sum1=0
for i in lis:
    sum1+=i
print(sum1)

34


In [116]:
n0=len(lis)
while n0>0:
    n0=n0-1
    print(n0,':', lis[n0])

5 : 8
4 : 9
3 : 8
2 : 4
1 : 2
0 : 3


In [119]:
import numpy as np
import pandas as pd

In [120]:
lis1=np.array([3,2,4,8,9,8])

In [121]:
lis1

array([3, 2, 4, 8, 9, 8])

In [122]:
type(lis1)

numpy.ndarray

In [127]:
dict2={'names':['james','david','Emmanuel','john'], 'age':[32,26,28,30], 'experience':[3,5,4,6]}

In [128]:
df=pd.DataFrame(dict2)

In [129]:
df

names  age  experience
0     james   32           3
1     david   26           5
2  Emmanuel   28           4
3      john   30           6

In [130]:
df.shape

(4, 3)

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   names       4 non-null      object
 1   age         4 non-null      int64 
 2   experience  4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes


In [3]:
#import libraries
import numpy as np
import pandas as pd

In [24]:
np1=np.array([3,5,7,9,11,13,15])

In [5]:
np1

array([ 3,  5,  7,  9, 11, 13, 15])

In [6]:
#check type
type(np1)

numpy.ndarray

In [19]:
sum1=np1.sum() #sum of elements

In [23]:
print(sum1)

63


In [20]:
len1=len(np1) # number of elements

### mean

In [18]:
np1.mean()

9.0

In [21]:
mean=sum1/len1
print(mean)

9.0


In [27]:
def summation(list1):
    sum3=0
    for number in list1:
        sum3=sum3+number
    return sum3     

def average1(list1):
    sum3=0
    for number in list1:
        sum3=sum3+number
    return sum3/len(list1)  
    

In [26]:
summation(np1)

63

In [31]:
average1(np1)

9.0

In [35]:
np.median(np1)

9.0

In [36]:
np1

array([ 3,  5,  7,  9, 11, 13, 15])

In [37]:
np2=np.array([3,7,15,11,5,9,13])

In [38]:
np.median(np2)

9.0

### Import a csv file into a python notebook

In [1]:
import requests

In [2]:
url="https://statso.io/wp-content/uploads/2024/02/food_orders_new_delhi.csv"
response=requests.get(url)
with open('food_order.csv','wb') as file:
    file.write(response.content)

In [4]:
food_order=pd.read_csv('food_order.csv')
food_order.head()

Order ID Customer ID Restaurant ID  Order Date and Time  \
0         1       C8270         R2924  2024-02-01 01:11:52   
1         2       C1860         R2054  2024-02-02 22:11:04   
2         3       C6390         R2870  2024-01-31 05:54:35   
3         4       C6191         R2642  2024-01-16 22:52:49   
4         5       C6734         R2799  2024-01-29 01:19:30   

  Delivery Date and Time  Order Value  Delivery Fee    Payment Method  \
0    2024-02-01 02:39:52         1914             0       Credit Card   
1    2024-02-02 22:46:04          986            40    Digital Wallet   
2    2024-01-31 06:52:35          937            30  Cash on Delivery   
3    2024-01-16 23:38:49         1463            50  Cash on Delivery   
4    2024-01-29 02:48:30         1992            30  Cash on Delivery   

  Discounts and Offers  Commission Fee  Payment Processing Fee  \
0            5% on App             150                      47   
1                  10%             198                      23   
2         15% New User             195                      45   
3                  NaN             146                      27   
4         50 off Promo             130                      50   

   Refunds/Chargebacks  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0

In [40]:
link="https://raw.githubusercontent.com/cloudxlab/ml/master/machine_learning/datasets/housing/housing.csv"
request=requests.get(link)

In [46]:
with open("housing.csv",'wb') as file:
    file.write(request.content)

In [47]:
housing_df=pd.read_csv("housing.csv")

In [53]:
housing_df.head(1)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY

In [54]:
housing_df.shape

(20640, 10)

In [56]:
housing_df.shape[1]

10

In [57]:
housing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [58]:
housing_df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [59]:
housing_df['total_rooms']

0         880.0
1        7099.0
2        1467.0
3        1274.0
4        1627.0
          ...  
20635    1665.0
20636     697.0
20637    2254.0
20638    1860.0
20639    2785.0
Name: total_rooms, Length: 20640, dtype: float64

In [63]:
print("sum: ",housing_df['total_rooms'].sum())
print('mean: ',housing_df['total_rooms'].mean())

sum:  54402150.0
mean:  2635.7630813953488


In [64]:
print('mean = {} and sum = {}'.format(housing_df['total_rooms'].mean(),housing_df['total_rooms'].sum()))

mean = 2635.7630813953488 and sum = 54402150.0


In [65]:
housing_df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000